# Generated by Django 4.2.5 on 2023-09-28 01:38

from django.db import migrations

def populate_roles(apps, schemaeditor):
    entries = {
        "developer": "A person tasked with completing issues",
        "scrum master": "The development team's coach",
        "product owner": "A team member who defines tasks",
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "The A Team",
        "bravo": "The B Team",
        "charlie": "The C Team",
        "delta": "The D Team",
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
        migrations.RunPython(populate_team)
    ]
